"""CreateShelter

Revision ID: 8e767898e4ca
Revises: 
Create Date: 2024-05-25 12:13:40.410134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision: str = '8e767898e4ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Abrigos',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('whats_app', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.DECIMAL(precision=19, scale=0), nullable=False),
    sa.Column('lng', sa.DECIMAL(precision=19, scale=0), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Abrigos')
    # ### end Alembic commands ###
